# Generated by Django 5.0 on 2023-12-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dbase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=50)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
